/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;


import javax.swing.*;
import java.lang.reflect.InvocationTargetException;

public class Main {

    public static void main(String[] args) {
        try {
            SwingUtilities.invokeAndWait(new Runnable() {
                @Override
                public void run() {
                    JFrame frame = new JFrame("STRATEGO");
                    GamePanel gamePanel = new GamePanel(new GameStratego());
                    frame.add(gamePanel);
                    //gamePanel.setFrame(frame);
                    frame.pack();
                    frame.setLocationRelativeTo(null);
                    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    gamePanel.start();
                    frame.setVisible(true);
                }
            });
        } catch (InvocationTargetException | InterruptedException e) {
            e.printStackTrace();
        }
    }
}
